disneystreaming/smithy4s

.github/workflows/ci.yml

Also bump memory for tests
[skip ci]

Disable release on main

---

.mergify.yml

Have mergify approve PRs

---

modules/core/src-js/smithy4s/JsConverters.scala
modules/core/test/src-js/smithy4s/JsConvertersSpec.scala

add js.Any => Document converter

---

modules/docs/src/01-overview/03-sbt.md
modules/docs/src/02-the-smithy-idl/01-smithy-idl.md
modules/docs/src/03-protocols/01-protocols.md

Again, a small typo.
I'm not done reading, so there is a chance I find other typos as I read, so if we wait a bit I might be able to add commits to the PR.

Fix typo in documentation

---

modules/tests/src/smithy4s/tests/PizzaSpec.scala

Header test cases were expecting a Json body even though there are no body fields defined in the response for headers

fix header tests

---

build.sbt

Manually checked the source jar and the sources are indeed there.

Add core's generated sources to jars

---

build.sbt
modules/core/src-2/Newtype.scala
modules/core/src-2/ShapeTag.scala
modules/core/src-3/Newtype.scala
modules/core/src-3/ShapeTag.scala
modules/core/src/smithy4s/internals/Hinted.scala
modules/docs/src/01-overview/02-quickstart.md
modules/docs/src/03-protocols/02-simple-rest-json/01-overview.md
modules/json/src/smithy4s/http/json/SchematicJCodec.scala
modules/json/test/src/smithy4s/http/json/SchematicJCodecTests.scala
modules/protocol/resources/META-INF/smithy/smithy4s.smithy
sampleSpecs/untagged.smithy

Adds support for untagged union as well as a bit of documentation regarding union encoding/decoding.

Support untagged union

---

modules/docs/src/04-codegen/01-customisation.md

The current docs are sort of confusing. Hopefully we can come up with some changes to clarify them. This is a start.

clarify @adtMember docs

---

modules/openapi/src/smithy4s/openapi/Smithy4sOpenApiExtension.scala
modules/openapi/src/smithy4s/openapi/UntaggedUnion.scala
modules/openapi/test/resources/foo.json
modules/openapi/test/resources/foo.smithy
modules/protocol/resources/META-INF/smithy/smithy4s.smithy
modules/protocol/src/smithy4s/api/UntaggedUnionTrait.java

TLDR: differences are subtle but existent
Payload differences:
Discriminated:
```
> curl -XPOST 'http://localhost:9000/david'
[{"greeting_type":"handwave","times":5}]
```
Untagged: 
```
> curl -XPOST 'http://localhost:9000/david'
[{"times":5}]
```
Default:
```
curl -XPOST 'http://localhost:9000/david'
[{"handwave":{"times":5}}]
```
For the full picture, here is the open API produced for each variant:
<details>
<summary>Discriminated</summary>
```json
{
"openapi": "3.0.2",
"info": {
"title": "HelloWorldService",
"version": "1.0.0"
},
"paths": {
"/{name}": {
"post": {
"operationId": "Hello",
"parameters": [
{
"name": "name",
"in": "path",
"schema": {
"type": "string"
},
"required": true
},
{
"name": "town",
"in": "query",
"schema": {
"type": "string"
}
}
],
"responses": {
"200": { …
```

Implement UntaggedUnion support in OpenApi extension

---

modules/json/src/smithy4s/http/json/SchematicJCodec.scala

Before:
```
[info] Benchmark                      (size)   Mode  Cnt         Score        Error  Units
[info] GoogleMapsAPIWriting.smithy4s     N/A  thrpt    5     39816.307 ±    983.413  ops/s
[info] NestedStructsWriting.smithy4s     128  thrpt    5    403630.790 ±  10781.265  ops/s
[info] PrimitivesWriting.smithy4s        N/A  thrpt    5   5866595.809 ± 208961.868  ops/s
```
After:
```
[info] Benchmark                      (size)   Mode  Cnt         Score        Error  Units
[info] GoogleMapsAPIWriting.smithy4s     N/A  thrpt    5     46183.832 ±    877.871  ops/s
[info] NestedStructsWriting.smithy4s     128  thrpt    5    460022.818 ±  41012.061  ops/s
[info] PrimitivesWriting.smithy4s        N/A  thrpt    5   6737206.295 ± 516062.120  ops/s
```

More efficient serialization of documents with ASCII keys

---

modules/json/src/smithy4s/http/json/SchematicJCodec.scala

Before:
```
[info] Benchmark                      (size)   Mode  Cnt         Score        Error  Units
[info] GoogleMapsAPIReading.smithy4s     N/A  thrpt    5     12944.819 ±    187.492  ops/s
[info] NestedStructsReading.smithy4s     128  thrpt    5     79215.733 ±   1431.124  ops/s
[info] PrimitivesReading.smithy4s        N/A  thrpt    5   1774113.192 ±  10739.137  ops/s
```
After:
```
[info] Benchmark                      (size)   Mode  Cnt         Score        Error  Units
[info] GoogleMapsAPIReading.smithy4s     N/A  thrpt    5     14744.585 ±    310.746  ops/s
[info] NestedStructsReading.smithy4s     128  thrpt    5     95762.699 ±    625.300  ops/s
[info] PrimitivesReading.smithy4s        N/A  thrpt    5   2207861.571 ±  27628.033  ops/s
```

More efficient parsing of documents

---

modules/json/src/smithy4s/http/json/SchematicJCodec.scala

Before:
```
[info] Benchmark                 Mode  Cnt         Score          Error  Units
[info] ADTWriting.smithy4sJson  thrpt    5   6374461.479 ±   173772.678  ops/s
```
After:
```
[info] Benchmark                 Mode  Cnt         Score          Error  Units
[info] ADTWriting.smithy4sJson  thrpt    5   7099680.308 ±   449450.566  ops/s
```

More efficient serialization discriminated ADTs

---

build.sbt
modules/aws-http4s/test/src/smithy4s/aws/http4s/Main.scala
modules/codegen/src/smithy4s/codegen/Renderer.scala
sampleSpecs/lambda.json

Closes #264. Let me know if I should revert the Lambda addition, it's generating ~350 files so it might slow the build down a little.

Fix streamed schema rendering

---

modules/codegen/src/smithy4s/codegen/Renderer.scala
modules/core/test/src/smithy4s/CollectionInTraitsSmokeSpec.scala
sampleSpecs/misc.smithy

Fixes https://github.com/disneystreaming/smithy4s/issues/266

Fix map rendering in traits (non-toplevel values)

---

modules/http4s-swagger/src-jvm-ce2/Compat.scala
modules/http4s-swagger/src-jvm-ce3/Compat.scala
modules/http4s-swagger/test/src/smithy4s/http4s/swagger/DocsSpec.scala

This would lead users to get a 404 on the default value.

Fix default swagger-ui path.

---

modules/codegen/src/smithy4s/codegen/IR.scala
modules/codegen/src/smithy4s/codegen/Renderer.scala
modules/codegen/src/smithy4s/codegen/SmithyToIR.scala
modules/core/src/smithy4s/schema/Schema.scala
modules/docs/src/04-codegen/01-customisation.md
modules/example/src/smithy4s/example/Age.scala
modules/example/src/smithy4s/example/DogName.scala
modules/example/src/smithy4s/example/FancyList.scala
modules/example/src/smithy4s/example/Name.scala
modules/example/src/smithy4s/example/PersonAge.scala
modules/example/src/smithy4s/example/UnwrappedFancyList.scala
modules/example/src/smithy4s/example/refined/Age.scala
modules/example/src/smithy4s/example/refined/FancyList.scala
modules/example/src/smithy4s/example/refined/Name.scala
modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala
modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy
modules/protocol/src/smithy4s/meta/RefinementTrait.java
sampleSpecs/refined.smithy

Updates refinement provider to be provided to the refined schema as an implicit.

make refinement provider implicit

---

modules/core/src/smithy4s/http/HttpContractError.scala
modules/json/src/smithy4s/http/json/Cursor.scala
modules/json/src/smithy4s/http/json/SchemaVisitorJCodec.scala
modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala

Cherry-picked https://github.com/disneystreaming/smithy4s/pull/371 commits into 0.0.15

Backported jsonName fixes

---

build.sbt
modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala
modules/codegen/src/smithy4s/codegen/package.scala
modules/example/resources/smithy4s.example.ReservedNameService.json
modules/example/src/smithy4s/example/Key.scala
modules/example/src/smithy4s/example/ListInput.scala
modules/example/src/smithy4s/example/OptionInput.scala
modules/example/src/smithy4s/example/ReservedNameService.scala
modules/example/src/smithy4s/example/SetInput.scala
modules/example/src/smithy4s/example/Value.scala
modules/example/src/smithy4s/example/package.scala
sampleSpecs/reservednames.smithy

add additional types to CollisionAvoidance list for reserved types
added additional Smithy spec to showcase handling of those cases
Fixed bug #389  when uncapitalizing name that starts with underscore

Collision Avoidance additions

---

modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala
modules/core/src/smithy4s/RefinementProvider.scala
modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecPropertyTests.scala
modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala
modules/scalacheck/src/smithy4s/scalacheck/SchemaVisitorGen.scala

Reverts disneystreaming/smithy4s#394

Revert "Range collision avoidance"

---

modules/codegen/src/smithy4s/codegen/Renderer.scala
modules/example/src/smithy4s/example/DefaultInMixinTest.scala
modules/example/src/smithy4s/example/DefaultInMixinUsageTest.scala
modules/example/src/smithy4s/example/package.scala
sampleSpecs/defaults.smithy

Handles part of #422. Fixes the issue where mixins were rendering defaults when they shouldn't

fix issue with default in mixin

---

modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala

add val for service inside ServiceBuilder 
https://github.com/disneystreaming/smithy4s/blob/edcadcd5f24da800372cf647f34cb42b775bf780/modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala#L58

make constructor for ServiceBuilder private , service is now a val

---

build.sbt
project/MimaVersionPlugin.scala

I botched the 0.16.0 release by merging an incomplete branch (from my local git repo). 
This is a PR to resolve conflict in the 0.16.0 branch. I will use https://github.com/disneystreaming/smithy4s/pull/457 to do the merge & release this time.
This is my mistake, sorry for the noise.

Merge main back into 0.16.0 before official release.

---

modules/core/src-2.12/ScalaCompat.scala
modules/core/src/smithy4s/http/internals/SchemaVisitorMetadataReader.scala
modules/core/src/smithy4s/http/internals/SchemaVisitorMetadataWriter.scala
modules/core/src/smithy4s/internals/SchemaDescription.scala
modules/core/src/smithy4s/schema/Primitive.scala

We're gonna need this exact same logic for XML parsing/serialisation.

Extract primitive string encoding/decoding logic. 

---

modules/mill-codegen-plugin/test/src/smithy4s/codegen/mill/Smithy4sModuleSpec.scala

I don't know what's going on here and why it even worked in the first place, but I _think_ it should be like this...

Fix potential typo

---

modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/bar/src/main/smithy/bar.smithy
modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/build.sbt
modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/foo/src/main/scala/foo.scala
modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/project/build.properties
modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/project/plugins.sbt
modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-no-compile/test
modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala
modules/docs/src/01-overview/05-sharing-specs.md
modules/mill-codegen-plugin/src/smithy4s/codegen/mill/Smithy4sModule.scala
modules/mill-codegen-plugin/test/resources/multi-module-no-compile/bar/smithy/bar.smithy
modules/mill-codegen-plugin/test/resources/multi-module-no-compile/foo/src/foo.scala
modules/mill-codegen-plugin/test/src/smithy4s/codegen/mill/Smithy4sModuleSpec.scala

- Allow opting out of dependency aggregation
- Add temporary implementation for Mill
Closes #484

Opt out of local dependencies

---

modules/codegen/src/smithy4s/codegen/Renderer.scala
modules/core/test/src/smithy4s/PatternSpec.scala
sampleSpecs/misc.smithy

Fix unicode escapes in generated strings

---

modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala

Add missing config scopes in codegen

---

modules/mill-codegen-plugin/src/smithy4s/codegen/mill/Smithy4sModule.scala

Adding stuff that's generated under `T.sources` is problematic

---

modules/protocol-tests/test/src/smithy4s/api/validation/RefinementTraitValidatorSpec.scala
modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy

- change pattern for `Import` to account for Scala 3 given imports.

protocol: support given import in refinements

---

modules/compliance-tests/src-ce2/smithy4s/compliancetests/Compat.scala
modules/compliance-tests/src-ce3/smithy4s/compliancetests/Compat.scala
modules/compliance-tests/src/smithy4s/compliancetests/ClientHttpComplianceTestCase.scala
modules/compliance-tests/src/smithy4s/compliancetests/ServerHttpComplianceTestCase.scala
modules/compliance-tests/test/src/smithy4s/compliancetests/WeaverComplianceTest.scala
modules/decline/src/Smithy4sCli.scala
modules/docs/src/03-protocols/05-compliance-tests.md

Add the second part of the initial PR
Co-authored-by: Jakub Kozłowski <kubukoz@gmail.com>

Add Server test for @httpRequestTests

---

.github/workflows/ci.yml

There is also coursier/cache-action that needs upgrading but we'll open a PR when https://github.com/coursier/cache-action/pull/418 is merged
References https://github.com/disneystreaming/smithy4s/issues/523

Move to coursier/setup-action

---

.github/workflows/ci.yml

The other jobs had been changed, but not this one looks like.

fix microsite workflow

---

modules/core/src/smithy4s/http/internals/SchemaVisitorMetadataReader.scala
modules/core/src/smithy4s/internals/DocumentDecoderSchemaVisitor.scala
modules/core/src/smithy4s/schema/Field.scala
modules/json/src/smithy4s/http/json/SchemaVisitorJCodec.scala

Use the functions introduced in #580.
Once this is merged, we can close #382.

Use get default func

---

build.sbt

Adds generated files to the sources jar for the dynamic module.
```console
➜ smithy4s (dynamic-sources) ✔ jar tf ~/.ivy2/local/com.disneystreaming.smithy4s/smithy4s-dynamic_2.13/dev-SNAPSHOT/srcs/smithy4s-dynamic_2.13-sources.jar
META-INF/MANIFEST.MF
smithy4s/
smithy4s/dynamic/
smithy4s/dynamic/internals/
smithy4s/dynamic/model/
DynamicSchemaIndexPlatform.scala
NodeToDocument.scala
smithy4s/dynamic/DynamicSchemaIndex.scala
smithy4s/dynamic/internals/DynamicEndpoint.scala
smithy4s/dynamic/internals/DynamicError.scala
smithy4s/dynamic/internals/DynamicErrorable.scala
smithy4s/dynamic/internals/DynamicLambdas.scala
smithy4s/dynamic/internals/DynamicModelCompiler.scala
smithy4s/dynamic/internals/DynamicOp.scala
smithy4s/dynamic/internals/DynamicSchemaIndexImpl.scala …
```

Dynamic generated sources

---

build.sbt

I did not do it for the `Test` configuration, but if you want me to, I can

Define source/resource generator together

---

modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala
modules/codegen/src/smithy4s/codegen/IR.scala
modules/codegen/src/smithy4s/codegen/LineSegment.scala
modules/codegen/src/smithy4s/codegen/Renderer.scala
modules/codegen/src/smithy4s/codegen/SmithyToIR.scala
modules/codegen/src/smithy4s/codegen/ToLine.scala
modules/docs/markdown/04-codegen/01-customisation.md
modules/example/src/smithy4s/example/Candy.scala
modules/example/src/smithy4s/example/DogName.scala
modules/example/src/smithy4s/example/NonEmptyCandies.scala
modules/example/src/smithy4s/example/NonEmptyListFormat.scala
modules/example/src/smithy4s/example/NonEmptyMapFormat.scala
modules/example/src/smithy4s/example/NonEmptyMapNumbers.scala
modules/example/src/smithy4s/example/NonEmptyNames.scala
modules/example/src/smithy4s/example/NonEmptyStrings.scala
modules/example/src/smithy4s/example/PersonAge.scala
modules/example/src/smithy4s/example/UnwrappedFancyList.scala
modules/example/src/smithy4s/example/collision/MapInput.scala
modules/example/src/smithy4s/example/collision/MyMap.scala
modules/example/src/smithy4s/example/collision/ReservedNameService.scala
modules/example/src/smithy4s/example/package.scala
modules/example/src/smithy4s/example/refined/NonEmptyList.scala
modules/example/src/smithy4s/example/refined/NonEmptyMap.scala
modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy
modules/protocol/src/smithy4s/meta/RefinementTrait.java
sampleSpecs/refined.smithy

Adds the ability to have refinements which abstract over a type parameter (or multiple parameters in the case of Map). See the added docs in the PR for more information.

Polymorphic refinements

---

modules/website/package.json
modules/website/yarn.lock

Merge all of 
- https://github.com/disneystreaming/smithy4s/pull/565
- https://github.com/disneystreaming/smithy4s/pull/564
- https://github.com/disneystreaming/smithy4s/pull/562
Into one PR so that it builds
Waiting on https://github.com/praveenn77/docusaurus-lunr-search/pull/89 to be merged / deploy. If it never is, we can close this or move on from lunr.

Docusaurus updates

---

build.sbt
modules/codegen/src/smithy4s/codegen/internals/Renderer.scala
modules/example/src/smithy4s/example/AString.scala
modules/example/src/smithy4s/example/AStructure.scala
modules/example/src/smithy4s/example/package.scala
sampleSpecs/quoted_string.smithy

resolves bug where string containing quotes is passed unescaped

escape quotes in string literal
