disneystreaming/smithy4s

build.sbt, modules/core/src/smithy4s/http/matchPath.scala, modules/core/test/src/smithy4s/http/MatchPathSpec.scala, modules/tests/src/smithy4s/tests/PizzaSpec.scala
Manual reproduction (before this change):
Start pizza service, send a request to `/`. This will fail with a 500 (index out of bounds: i = 0, array size = 0) regardless of the backend, as long as it uses `HttpEndpoint.matches`.
=> Don't raise 500 when path is too short

build.sbt, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/test/src/smithy4s/EmptyServiceSmokeSpec.scala, sampleSpecs/empty.smithy
Fixes https://github.com/disneystreaming/smithy4s/issues/3
=> Make generated code from empty services compile

modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/src-2/TypeAliases.scala, modules/core/src-3/TypeAliases.scala, modules/core/src/smithy4s/Service.scala, modules/core/src/smithy4s/package.scala, modules/core/test/src/smithy4s/EmptyServiceSmokeSpec.scala, modules/core/test/src/smithy4s/TypeInferenceSmokeSpec.scala, modules/example/src/smithy4s/example/package.scala, modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala
By changing the type alias use for monadic algebra.
=> Improve type inference in Scala 3

README.md, build.sbt, modules/codegen-cli/src/smithy4s/codegen/cli/CodegenCommand.scala, modules/codegen-cli/src/smithy4s/codegen/cli/DumpModel.scala, modules/codegen-cli/src/smithy4s/codegen/cli/DumpModelCommand.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Main.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Options.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Smithy4sCommand.scala, modules/codegen-cli/test/src/smithy4s/codegen/cli/CommandParsingSpec.scala, modules/codegen/src/smithy4s/codegen/Codegen.scala, modules/codegen/src/smithy4s/codegen/ModelLoader.scala
Closes #20. Probably incomplete, I'm not sure if the output is all that's necessary to read a model.
=> Add JSON dump command

modules/aws-kernel/src/smithy4s/aws/AwsSignature.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/src/smithy4s/Endpoint.scala, modules/core/src/smithy4s/http/UnknownErrorResponse.scala, modules/core/src/smithy4s/http/internals/URIEncoderDecoder.scala, modules/core/src/smithy4s/package.scala, modules/example/src/smithy4s/example/FooService.scala, modules/example/src/smithy4s/example/ObjectService.scala, modules/example/src/smithy4s/example/StreamedObjects.scala
Also move URIEncoderDecoder to http.internals package and UnkownErrorResponse to the http package
=> Render ShapeId for operations 

modules/protocol/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, modules/protocol/src/smithy4s/api/validation/HttpHeaderValidator.java, modules/protocol/test/src/smithy4s/api/validation/HttpHeaderValidatorSpec.scala
Adds validator to make sure headers cannot be set if they are automatically set down the line.
Closes #28.
=> add header validator

README.md, modules/codegen-plugin/src/sbt-test/codegen-plugin/custom-settings/build.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/build.sbt, modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala
Closes #34.
The issue was that the sbt plugin was auto-adding the `smithy4s-core` dependency. This worked in all cases except for Scala JS since that would require the use of `%%%`. We could have updated the plugin to use `%%%`, but that would require the Scala JS SBT plugin be present on all projects using it, which we do not want to require.
=> remove core dependency auto-add from sbt plugin

build.sbt, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/test/src/smithy4s/ShapeIdHintsSmokeSpec.scala, modules/example/src/smithy4s/example/GetFooOutput.scala, modules/example/src/smithy4s/example/GetObjectInput.scala, modules/example/src/smithy4s/example/GetObjectOutput.scala, modules/example/src/smithy4s/example/GetStreamedObjectInput.scala, modules/example/src/smithy4s/example/PutObjectInput.scala, modules/example/src/smithy4s/example/PutStreamedObjectInput.scala, sampleSpecs/weather.smithy
This is still a WIP, but the idea is adding a few test cases to ensure the fix in #36 is working.
It seems like there may be an easier way than the approach I am taking here, so please let me know if there is. I couldn't find a great way to get the hints from a schema without compiling the schema.
The union test is not working as of right now, but the other two are.
=> Add smoke tests to check for hints on schemas

.github/workflows/ci.yml
This will make it so we can manually trigger a build that will publish a snapshot.
=> add flag to CI to trigger snapshot build

build.sbt, modules/aws-kernel/src/smithy4s/aws/AwsSignature.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/src/smithy4s/http/HttpEndpoint.scala, modules/core/src/smithy4s/http/Method.scala, modules/core/src/smithy4s/http/PathSegment.scala, modules/core/src/smithy4s/http/internals/PathEncode.scala, modules/core/src/smithy4s/http/internals/SchematicPathEncoder.scala, modules/core/src/smithy4s/http/internals/URIEncoderDecoder.scala, modules/core/src/smithy4s/http/internals/package.scala, modules/core/src/smithy4s/package.scala, modules/core/test/src-js/smithy4s/JsConvertersSpec.scala, modules/core/test/src/smithy4s/TypeInferenceSmokeSpec.scala, modules/core/test/src/smithy4s/http/internals/PathParsingSpec.scala, modules/core/test/src/smithy4s/http/internals/PathSpec.scala, modules/example/src/smithy4s/example/FooService.scala, modules/example/src/smithy4s/example/ObjectService.scala, modules/protocol/test/src/smithy4s/api/validation/DiscriminatedUnionValidatorSpec.scala, sampleSpecs/metadata.smithy, sampleSpecs/pizza.smithy
Derive HttpEndpoint from Hint instead of relying on subtyping
This derives the HttpEndpoint instance associated to an Endpoint, by searching smithy.api.Http in the the Endpoint's hints, and compiling the found data to the correct interface, by means of Schematic.
The rationale is the following :
1. allow for dynamically instantiated service to have HttpService without any bespoke processing.
2. open the door for splitting the http package away from the core module
=> Derive http endpoints from hints

build.sbt, modules/json/src/smithy4s/http/json/SchematicJCodec.scala, modules/json/test/src/smithy4s/http/json/SchematicJCodecTests.scala, sampleSpecs/discriminated.smithy
Fixes #48. Implementation by @Baccata.
=> Allow decoding of discriminated unions with whitespace

build.sbt, modules/benchmark/src/main/scala/Codecs.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/test/src/smithy4s/ProductSerialSmokeSpec.scala, modules/example/src/smithy4s/example/Foo.scala, modules/example/src/smithy4s/example/LowHigh.scala, modules/example/src/smithy4s/example/ObjectService.scala, sampleSpecs/product.smithy
Using full-qualified-names because users encounter issues when they use `Product` as a shape name.
=> Use FQNs in rendered `Product` and `Serializable` inheritance

.envrc, .gitignore, README.md, flake.lock, flake.nix, shell.nix
This is just for local usage, I did a POC of using the same shell with the same versions in CI (#68) but it only proved my fears - it takes too long for the initial setup so it doesn't really improve the situation much, regardless of how good Nix is at caching (ephemeral runners don't help).
=> Add nix shell

.github/workflows/ci.yml
Now that we have the version pulling the latest stable for snapshots, we should enable publishing the website on snapshot builds.
=> allow site publish for snapshots

modules/core/src/smithy4s/http/HttpEndpoint.scala, modules/core/src/smithy4s/http/internals/PathEncode.scala, modules/core/src/smithy4s/http/internals/SchematicPathEncoder.scala, modules/core/src/smithy4s/http/internals/URIEncoderDecoder.scala, modules/core/test/src/smithy4s/http/internals/PathSpec.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sClientEndpoint.scala
Should close #72.
Internal ref: ASTX-2675
=> Leave URI encoding to interpreters

modules/codegen/test/src/smithy4s/codegen/SmithyToIRSpec.scala, modules/core/test/src/smithy4s/HintMaskSpec.scala, modules/core/test/src/smithy4s/ShapeIdHintsSmokeSpec.scala, modules/json/test/src/smithy4s/http/json/SchematicJCodecTests.scala, modules/openapi/src/smithy4s/openapi/DiscriminatedUnion.scala, modules/openapi/src/smithy4s/openapi/Smithy4sOpenApiExtension.scala, modules/openapi/test/resources/foo.json, modules/openapi/test/resources/foo.smithy, modules/protocol/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService, modules/protocol/src/smithy4s/api/validation/DiscriminatedUnionValidator.java, modules/protocol/test/src/smithy4s/api/validation/DiscriminatedUnionValidatorSpec.scala, sampleSpecs/discriminated.smithy
Also updates discriminated union validator to check that target structures do not contain the discriminator field explicitly
=> add support for discriminated union conversion to openapi

modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/core/src/smithy4s/HintMask.scala, modules/example/src/smithy4s/example/ArbitraryDataTest.scala, modules/example/src/smithy4s/example/Foo.scala, modules/example/src/smithy4s/example/GetFooOutput.scala, modules/example/src/smithy4s/example/GetObjectInput.scala, modules/example/src/smithy4s/example/GetObjectOutput.scala, modules/example/src/smithy4s/example/GetStreamedObjectInput.scala, modules/example/src/smithy4s/example/GetStreamedObjectOutput.scala, modules/example/src/smithy4s/example/LowHigh.scala, modules/example/src/smithy4s/example/NoMoreSpace.scala, modules/example/src/smithy4s/example/ObjectService.scala, modules/example/src/smithy4s/example/PutObjectInput.scala, modules/example/src/smithy4s/example/PutStreamedObjectInput.scala, modules/example/src/smithy4s/example/ServerError.scala
Since Hint keys are now ShapeTags, they are conceptually no longer
specific to keys, so might as well render them for all shapes.
=> Render ShapeTags for everything

build.sbt, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/example/resources/smithy4s.example.ImportService.json, modules/example/src/smithy4s/example/ImportService.scala, modules/example/src/smithy4s/example/import_test/OpOutput.scala, modules/example/src/smithy4s/example/package.scala, sampleSpecs/import.smithy, sampleSpecs/operation.smithy
Fixes an issue where imports were being filtered out if they were for a sub-package.
=> fix for imports from sub-packages

build.sbt, modules/codegen/src/smithy4s/codegen/Renderable.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/example/resources/smithy4s.example.imp.ImportService.json, modules/example/src/smithy4s/example/error/NotFoundError.scala, modules/example/src/smithy4s/example/imp/ImportService.scala, modules/example/src/smithy4s/example/imp/package.scala, modules/example/src/smithy4s/example/package.scala, sampleSpecs/import.smithy, sampleSpecs/importerror.smithy
=> remove generation of redundant package imports

.github/workflows/ci.yml, build.sbt, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/PostProcessor.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/core/test/src/smithy4s/PackedInputsSmokeSpec.scala, modules/docs/src/04-codegen/01-customisation.md, modules/protocol/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService, modules/protocol/resources/META-INF/smithy/manifest, modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy, modules/protocol/src/smithy4s/meta/PackedInputsTrait.java, sampleSpecs/packedInputs.smithy
Closes https://github.com/disneystreaming/smithy4s/issues/114
* Adds a way for users to tweak rendering of services methods, and substitute a list of parameters in methods for a single case-class parameter (which smithy4s uses under the hood anyway), corresponding to the smithy shape of the operation's input (when present). This might offer better UX in some occurences.
* Adds documentation
=> Adds a way to get packed inputs in operations

build.sbt, modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/core/test/src/smithy4s/BigStructSmokeSpec.scala, modules/core/test/src/smithy4s/EnumWithSymbolsSmokeSpec.scala, modules/schematic-core/src/generated/struct.scala, project/SchematicBoilerplate.scala, sampleSpecs/empty.smithy, sampleSpecs/misc.smithy
Fixes https://github.com/disneystreaming/smithy4s/issues/129 
Fixes https://github.com/disneystreaming/smithy4s/issues/128
* Renders correct schemas for structures of arity > 22 
* Renders correct names for enum values, even in worst case scenario (purely-symbolic enum value)
* Adds smoke tests to check both fixes
=> Rendering fixes

modules/codegen-plugin/src/sbt-test/codegen-plugin/custom-settings/build.sbt, modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala
The goal is the following: having codegen dependencies as
regular sbt libraryDependencies will allow tools (like scala-
steward) to work with them
=> Add a smithy4s config to import codegen dependencies

modules/http4s-swagger/src-jvm/smithy4s/http4s/swagger/Docs.scala, modules/http4s-swagger/test/src/smithy4s/http4s/swagger/DocsSpec.scala
provided additional handling for value specified as docs path when there is trailing slash and index.html afterwards
=> handle docs path

modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/example/src/smithy4s/example/ArbitraryData.scala
Includes a couple of changes to codegen rendering to fix compilation of code generated by smithy4s from the [AWS Kinesis service definition](https://github.com/aws/aws-sdk-js-v3/blob/v3.63.0/codegen/sdk-codegen/aws-models/kinesis.json).
**[Change codegen to render fully qualified smithy4s types](https://github.com/disneystreaming/smithy4s/pull/166/commits/9b08aadebdf19d9231fb5e70dea7bf574d6369b0)**
Changes codegen to render smithy4s.Timestamp and smithy4s.Document instead of importing these and using just the type name. 
Without this change a custom Timestamp type aliasing smithy4s.Timestamp (as is the case for the AWS Kinesis service) results in compilation error due to type collisions.
Fixes https://github.com/disneystreaming/smithy4s/issues/163
**[Fix codegen rendering of member hints …
=> Fix codegen rendering for AWS Kinesis service

modules/aws-http4s/src/smithy4s/aws/http4s/AwsHttp4sBackend.scala
Before this change requests were using an incorrect `Content-Type` header `application/octet-stream` rather than using the `Content-Type` header defined by the `AwsProtocol`. This was because `withEntity` on http4s client requests sets the headers according to the implicit `EntityEncoder` and the simple `HttpRequest` body is `Option[Array[Byte]]`.
This changes the request so that the headers from the simple `HttpRequest` take priority over those set by `withEntity`.
Fixes https://github.com/disneystreaming/smithy4s/issues/167
Here's an example for Kinesis ListShards operation:
<details>
<summary>Before</summary>
```sh
curl \
--request POST \
--url 'https://kinesis.us-east-1.amazonaws.com/' \
--header 'Authorization: <REDACTED>' \
--header 'host: kinesis.us-east-1.amazonaws.com' \
--header …
```
=> Fix Content-Type for AWS service requests using http4s client

modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/example/resources/smithy4s.example.ObjectService.json, modules/example/src/smithy4s/example/Foo.scala, sampleSpecs/example.smithy
BigInt's were previously rendered as BigInteger on accident. BigInteger is not a type in scala, it is `scala.math.BigInt` which wraps java's `BigInteger` (and adds an optimization where it uses a Long to back it when the number is small enough)
=> fix rendering of big integers

modules/http4s/src/smithy4s/http4s/EntityCompiler.scala, modules/tests/src/smithy4s/tests/PizzaSpec.scala
Makes body empty instead of `{}` when the metadata contains all fields in response
=> http4s make body empty when metadata is total

modules/aws-http4s/src/smithy4s/aws/http4s/AwsHttp4sBackend.scala, modules/aws-http4s/src/smithy4s/aws/http4s/package.scala, modules/aws/src/smithy4s/aws/AwsClient.scala, modules/aws/src/smithy4s/aws/AwsEnvironment.scala
The purpose of this is twofold:
1. Don't require the full power of `Async` to construct an AWS client
2. Allow building the interpreter in steps: checking the service can be done without doing any credential-related work, then the rest can be executed in a resource (this would be valuable to me for smithy-playground).
=> Loosen constraints in aws-http4s

modules/dynamic/src/smithy4s/dynamic/internals/DynamicModelCompiler.scala
The name would use the operation's name + "Error" as the namespace and kept the operation's name.
=> Fix DynamicError's shapeId

.github/workflows/ci.yml, modules/codegen-plugin/src/sbt-test/codegen-plugin/custom-settings/project/build.properties, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/project/build.properties, modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala
This greatly simplifies the caching logic and solves the problem I was having - if you run `~compile` on a module with smithy specs, they actually weren't re-generated and re-compiled if you changed a spec.
I've confirmed on my project that this change addresses the problem.
=> Use a simpler mechanism to detect file changes

modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala
Use `FileFunction` mechanism to more accurately cache the input and output files of the task, as well as react to file changes for more interactive experience.
This combination _seems_ to remove the issues I was seeing before with Zinc.
=> Recursively return all the generated files

build.sbt, modules/docs/src/01-overview/04-cli.md
We have just a few commands let's have them in the docs for a quick reference. Who knows who it might help.
=> Improve CLI docs

modules/codegen-plugin/src/sbt-test/codegen-plugin/dependencies-only/build.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/dependencies-only/project/build.properties, modules/codegen-plugin/src/sbt-test/codegen-plugin/dependencies-only/project/plugins.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/dependencies-only/test, modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala
The recent changes related to the sbt-plugin altered how it decides when to run the codegen and when it is not necessary. Unfortunately, we missed the fact that there are two components of the cache key that are needed: 1) the files if there are any that are colocated, 2) the dependencies that smithy4s can pull down to extract smithy files from jars.
@keynmol my sbt wizardry is not quite capable of keeping what you did and putting into place the changes necessary to fix the dependencies. If you want to take a crack at that, then please feel free. In the meantime, I am going to merge this so we can unblock some other internal projects.
=> Fix sbt plugin regression

modules/json/src/smithy4s/http/json/SchematicJCodec.scala
Currently smithy4s spends more than 1/3 of CPU cycles on creation of document encoders during serialization of data structures:
This small patch fixes that by storing document encoders locally in codecs and increases throughput of serialization of data structures on ~50%.
=> Memorize document encoders

modules/json/src/smithy4s/http/json/SchematicJCodec.scala
Default Java's base64 encoder do padding according to RFC-4648
=> Do padding of base64 encoded strings

build.sbt, modules/core/src/smithy4s/Timestamp.scala, modules/dynamic/src/smithy4s/dynamic/DynamicSchemaIndex.scala, modules/dynamic/src/smithy4s/dynamic/internals/DynamicModelCompiler.scala, modules/dynamic/test/src-jvm/smithy4s/dynamic/DecodingSpec.scala, modules/dynamic/test/src-jvm/smithy4s/dynamic/DynamicJsonProxySpec.scala, modules/dynamic/test/src-jvm/smithy4s/dynamic/Http4sDynamicPizzaClientSpec.scala, modules/dynamic/test/src-jvm/smithy4s/dynamic/PlatformUtils.scala, modules/tests/src/smithy4s/tests/PizzaClientSpec.scala
With the recent schema overhaul, fields and alts are supposed to carry hints directly on them. 
Fixes #244
@kubukoz, would you be so kind as to turning your repro repo (which I've tested against) into some unit tests in the dynamic module before we merge this ?
=> Fix dynamic compiler applying field/alt hints at the wrong level

modules/json/src/smithy4s/http/json/SchematicJCodec.scala, modules/json/test/src/smithy4s/http/json/SchematicJCodecTests.scala
Before:
```
[info] Benchmark                               (size)   Mode  Cnt        Score       Error  Units
[info] ExtractFieldsReading.smithy4sDocument        1  thrpt    5  2103571.715 ± 53265.991  ops/s
[info] ExtractFieldsReading.smithy4sDocument       10  thrpt    5   222313.388 ±  5891.141  ops/s
[info] ExtractFieldsReading.smithy4sDocument      100  thrpt    5    13535.324 ±   180.397  ops/s
[info] ExtractFieldsReading.smithy4sDocument     1000  thrpt    5      333.161 ±     7.923  ops/s
```
After:
```
[info] Benchmark                               (size)   Mode  Cnt        Score       Error  Units
[info] ExtractFieldsReading.smithy4sDocument        1  thrpt    5  3128058.525 ± 91970.963  ops/s
[info] ExtractFieldsReading.smithy4sDocument       10  thrpt    5   291746.400 ± …
```
=> More efficient reading and writing of JSON documents

build.sbt, modules/core/test/src-js/smithy4s/JsConvertersSpec.scala, modules/core/test/src-js/smithy4s/Platform.scala, modules/core/test/src-jvm/smithy4s/Platform.scala, modules/core/test/src-jvm/smithy4s/TimestampSpec.scala, modules/core/test/src/smithy4s/BigStructSmokeSpec.scala, modules/core/test/src/smithy4s/CollectionInTraitsSmokeSpec.scala, modules/core/test/src/smithy4s/DocumentSpec.scala, modules/core/test/src/smithy4s/EmptyServiceSmokeSpec.scala, modules/core/test/src/smithy4s/EnumWithSymbolsSmokeSpec.scala, modules/core/test/src/smithy4s/HintMaskSpec.scala, modules/core/test/src/smithy4s/HintsSpec.scala, modules/core/test/src/smithy4s/NewtypesSpec.scala, modules/core/test/src/smithy4s/PackedInputsSmokeSpec.scala, modules/core/test/src/smithy4s/ProductSerialSmokeSpec.scala, modules/core/test/src/smithy4s/SchemaEqualitySmokeSpec.scala, modules/core/test/src/smithy4s/ShapeIdHintsSmokeSpec.scala, modules/core/test/src/smithy4s/SummonSmokeSpec.scala, modules/core/test/src/smithy4s/expect.scala, modules/core/test/src/smithy4s/http/CaseInsensitiveSpec.scala, modules/core/test/src/smithy4s/http/MatchPathSpec.scala, modules/core/test/src/smithy4s/http/StringAndBlobSpec.scala, modules/core/test/src/smithy4s/http/internals/MetadataSpec.scala, modules/core/test/src/smithy4s/http/internals/PathSpec.scala, modules/json/test/src/smithy4s/http/json/DocumentPropertyTests.scala, modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala, modules/json/test/src/smithy4s/http/json/SchematicJCodecPropertyTests.scala
This switches weaver to Munit. We attempt to reduce the diff via the
creation of an `expect` object that exposes signatures somewhat similar
to weaver's expectations.
The reason for doing this is the impending cross-building to scala-native
=> Switch weaver to munit in core Module.

modules/aws/src/smithy4s/aws/AwsCredentialsProvider.scala
=> Fix resource leak in AWS refresh loop

build.sbt, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/ToLine.scala, modules/example/src/smithy4s/example/AddBrandsInput.scala, modules/example/src/smithy4s/example/BrandService.scala, modules/example/src/smithy4s/example/common/BrandList.scala, modules/example/src/smithy4s/example/common/package.scala, modules/example/src/smithy4s/example/package.scala, sampleSpecs/brands.smithy, sampleSpecs/brandscommon.smithy
An issue was discovered where extra imports are added to services under the following conditions:
- Service has an operation which has an input parameter from another namespace
- Said input parameter is a newtype
The reason this happens is because the service unpacks the newtype to directly point at the inner type of the newtype. So once this unpacking happens, the import is no longer needed. This issue is masked in the rendering of structures, for example, because they use the newtype inside the construction of the schema.
This fix is kind of a patch, the real fix is to create the import resolution based on carrying fully qualified name information through the rendering process before cleaning up at the end (as we've discussed we want to do).
=> fix imports for newtypes from other packages

modules/codegen-cli/src/smithy4s/codegen/cli/CodegenCommand.scala, modules/codegen-cli/src/smithy4s/codegen/cli/DumpModel.scala, modules/codegen-cli/src/smithy4s/codegen/cli/DumpModelCommand.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Options.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Smithy4sCommand.scala, modules/codegen-cli/test/src/smithy4s/codegen/cli/CommandParsingSpec.scala, modules/codegen-plugin/src/smithy4s/codegen/CodegenPlugin.scala, modules/codegen/src/smithy4s/codegen/Codegen.scala, modules/codegen/src/smithy4s/codegen/CodegenArgs.scala, modules/codegen/src/smithy4s/codegen/ModelLoader.scala
Fixes dependency resolution from a maven repository that requires authentication (tested against a CodeArtifact repo with `sbt-codeartifact`).
=> Use internal sbt dependency resolution in codegen-plugin

modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/core/src/smithy4s/schema/Alt.scala, modules/core/test/src/smithy4s/AdtSmokeSpec.scala, modules/docs/src/03-protocols/02-simple-rest-json/01-overview.md, modules/docs/src/04-codegen/01-customisation.md, modules/docs/src/04-codegen/02-unions.md, modules/example/src/smithy4s/example/OrderType.scala, sampleSpecs/adtMember.smithy
Additionally, add documentation regarding unions and their encodings
=> Render Unit in unions as case objects

modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/codegen/src/smithy4s/codegen/ToLine.scala, modules/core/src/smithy4s/http/internals/MetaEncode.scala, modules/docs/src/04-codegen/01-customisation.md, modules/example/src/smithy4s/example/SomeIndexSeq.scala, modules/example/src/smithy4s/example/SomeVector.scala, modules/example/src/smithy4s/example/package.scala, modules/protocol/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService, modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy, modules/protocol/src/smithy4s/meta/IndexedSeqTrait.java, modules/protocol/src/smithy4s/meta/VectorTrait.java, sampleSpecs/example.smithy, sampleSpecs/misc.smithy, smithy-build.json
Adds a mechanism for users to customise the collection type used when generating Scala code from smithy `list` shapes. 
Users can now opt-in `Vector` or `IndexedSeq`. `List` remains the default collection type.
=> Add @vector and @indexedSeq 

modules/json/src/smithy4s/http/json/Cursor.scala
On JDK 17 it gives up to 2x times speed up on parsing of JSON arrays (see `ArrayOfBooleansReading`, `ArraySeqOfBooleansReading`, `ListOfBooleansReading`, `VectorOfBooleansReading`) and up to 1.3x times speed up on JSON objects (see `GeoJSONReading`) by the cost of slow down parsing of top-level JSON values (see `Base64Reading`, `BigIntReading`, `IntReading`, `StringOfAsciiCharsReading`, `StringOfEscapedCharsReading`, `StringOfNonAsciiCharsReading`)
```
[info] Benchmark                                  (size)   Mode  Cnt         Score         Error  Units
[info] ADTReading.smithy4sJson                       N/A  thrpt    5   1720855.406 ±   44766.774  ops/s
[info] AnyValsReading.smithy4sJson                   N/A  thrpt    5   1930181.226 ±  115372.354  ops/s
[info] …
```
=> More efficient parsing of JSON arrays and objects

modules/json/src/smithy4s/http/json/Cursor.scala, modules/json/src/smithy4s/http/json/SchemaVisitorJCodec.scala, modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala
Fixing of overlooked capacity sizing. Below are results of benchmarks for real-world messages on JDK 17.
```
[info] Benchmark                                  (size)   Mode  Cnt         Score         Error  Units
[info] GoogleMapsAPIReading.smithy4sJson             N/A  thrpt    5     15125.336 ±      34.299  ops/s
[info] OpenRTBReading.smithy4sJson                   N/A  thrpt    5    177589.601 ±    2958.052  ops/s
[info] TwitterAPIReading.smithy4sJson                N/A  thrpt    5     34670.625 ±    1334.928  ops/s
```
##
```
[info] Benchmark                                  (size)   Mode  Cnt         Score         Error  Units
[info] GoogleMapsAPIReading.smithy4sJson             N/A  thrpt    5     16034.257 ±      40.094  ops/s
[info] OpenRTBReading.smithy4sJson …
```
=> Reduce CPU usage on access to java.util.HashTable

build.sbt, modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/example/src/smithy4s/example/CommonFieldsOne.scala, modules/example/src/smithy4s/example/CommonFieldsTwo.scala, modules/example/src/smithy4s/example/EmptyMixin.scala, modules/example/src/smithy4s/example/MixinErrorExample.scala, modules/example/src/smithy4s/example/MixinExample.scala, modules/example/src/smithy4s/example/TestEmptyMixin.scala, modules/example/src/smithy4s/example/TestMixinAdt.scala, sampleSpecs/mixins.smithy
The purpose of this PR is to use smithy 2.0 mixins to generate traits in the codegen.
Note this PR is based off of the `0.0.15-smithy2` branch.
See the examples in the PR for how traits look and are used.
=> first pass at using mixins to create traits

build.sbt, modules/core/src/smithy4s/ShapeId.scala, modules/core/src/smithy4s/http/ErrorAltPicker.scala, modules/core/src/smithy4s/http/Metadata.scala, modules/core/src/smithy4s/http/UnknownErrorResponse.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sClientEndpoint.scala, modules/tests/src/smithy4s/tests/PizzaClientSpec.scala
Remove the best-effort error-decoding logic
Now, when a client gets an unsuccessful response from a server, it'll
try to inspect the X-Error-Type header first, and then will try to match
the received status code against the errors it knows about
(provided the code in question is uniquely used)
If the client cannot infer a unique alternative based on this
information, it'll raise a generic "UnknownErrorResponse"
=> Best-effort error-decoding fix

modules/core/src/smithy4s/http/HttpContractError.scala, modules/json/src/smithy4s/http/json/Cursor.scala, modules/json/src/smithy4s/http/json/SchemaVisitorJCodec.scala, modules/json/test/src/smithy4s/http/json/SchemaVisitorJCodecTests.scala
On top of that, I include a change to improve the `message` of such error so that we know the path where a field was expected but not found.
=> Use jsonName on Missing required field error

.github/workflows/ci.yml, .mergify.yml
Add a job that acts as a checkpoint to signal to
mergify that all jobs of the matrix (in this case `build`) were
successful.
This would address https://github.com/disneystreaming/smithy4s/issues/372
=> Build checkpoint for mergify

.mergify.yml
we can see that it does not match in swagger-ui pr (it would not have in all scenario because the bump is not a patch bump)
=> Refer to the job name, not the steps

modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/build.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/src/main/scala/Main.scala, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/test, modules/codegen/src/smithy4s/codegen/CollisionAvoidance.scala, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/core/src/smithy4s/RefinementProvider.scala, modules/example/src/smithy4s/example/ArbitraryData.scala, modules/example/src/smithy4s/example/TestTrait.scala
Makes it so that all trait schemas are wrapped in schema.recursive. This is one method of dealing with the bug from #383. I am fine if we decide to go another direction, but wanted to give this a shot.
Closes #383
=> fix init ordering bug

.github/dependabot.yml
**Summary**
This will keep stuff like `- uses: actions/checkout@v2` updated (v3 is latest) in Github Actions, e.g. in the [CI action](https://github.com/disneystreaming/smithy4s/blob/main/.github/workflows/ci.yml#L50)
> Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer. When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file are kept up to date.
~ https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Auto-update GitHub Action dependencies

.github/workflows/ci.yml, build.sbt, project/MimaVersionPlugin.scala, project/plugins.sbt
Enables Mima Checks on the following modules (all variants of scala versions/CE versions)
- json
- http4s
- core
=> Enable Mima Checks

.github/workflows/ci.yml, build.sbt, project/MimaVersionPlugin.scala, project/Smithy4sPlugin.scala
Adds a matrix-specific command to allow mima to run more specifically
=> Fix mima command to run more quickly

modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/example/src/smithy4s/example/MixinOptionalMember.scala, modules/example/src/smithy4s/example/MixinOptionalMemberDefaultAdded.scala, modules/example/src/smithy4s/example/MixinOptionalMemberOverride.scala, sampleSpecs/mixins.smithy
Update that will make it so case classes no longer extend mixin-related traits when they contain fields that do not match in type (optional vs. required, etc). See examples in this PR for more cases.
Resolves #422.
=> update how mixins and structs with mismatches are handled

modules/codegen-plugin/src/smithy4s/codegen/JsonConverters.scala, modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala, modules/codegen/src/smithy4s/codegen/ModelLoader.scala, modules/codegen/test/src/smithy4s/codegen/DefaultRenderModeSpec.scala, modules/codegen/test/src/smithy4s/codegen/TestUtils.scala, modules/core/test/src/smithy4s/IntEnumSmokeSpec.scala, modules/json/test/src/smithy4s/http/json/FaceCard.scala
This exhaustively captures the codegenArgs as a way to invalidate SBT's cache to re-trigger codegen every time something changes.
This uses SBT's JsonFormat, converting os-lib's paths into file hashes. In theory, when a local file changes (say, a dependency snapshot), the cache should now be invalidated and trigger a regeneration.
Additionally, this disable jar caching in the Smithy Model assembler that loads local jars. This prevents users who experiment with snapshot artifacts from having to exit/restart SBT when issuing a new local snapshot . 
Unfortunately, this is pretty hard to test in an automated manner.
=> Exhaustively capture the codegen input for cache invalidation

build.sbt, modules/protocol-tests/test/src/smithy4s/api/validation/RefinementTraitValidatorSpec.scala, modules/protocol/resources/META-INF/smithy/smithy4s.meta.smithy
Allow imports and classpaths in refinements to contain `_root_` at the beginning of them.
=> support root imports in refinements

modules/http4s-swagger/src-jvm/smithy4s/http4s/swagger/Docs.scala, modules/http4s-swagger/test/src/smithy4s/http4s/swagger/DocsSpec.scala
That means that what was previously
`"urls": ["/example.SomeSpec.yaml"]`
will now be
`"urls": ["./docs/specs/example.SomeSpec.yaml"]`
`docs` is from the path the user provided when initializing the route, `specs` is added in this PR.
This is to be able to write `./specs/example.SomeSpec.yaml` in the `urls` array for swagger initialization. Rather than asking for `/example.SomeSpec.yaml`, we ask for `./example.SomeSpec.yaml` and because this conflicts with other paths such as `./swagger-ui.css` I've decided to serve specs under a specific path instead.
In the browser, this ends up being:
In the screenshot above, we see requests from the browser after loading `/docs/index.html` from behind a proxy at `/admin/docs/index.html`.  Before, the request would …
=> Use a document relative url for specs

modules/docs/src/01-overview/02-quickstart.md, modules/docs/src/03-protocols/02-simple-rest-json/03-client.md, modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala, modules/http4s/src/smithy4s/http4s/SmithyHttp4sReverseRouter.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sClientEndpoint.scala, modules/http4s/test/src-jvm/smithy4s/http4s/Http4sDynamicPizzaClientSpec.scala, modules/http4s/test/src/smithy4s/http4s/Http4sPizzaClientSpec.scala, modules/http4s/test/src/smithy4s/http4s/RecursiveInputSpec.scala
Ok so this is obviously not backwards compatible at all as it changes the interface that is exposed to users
I'm marking it draft to signal that this is more about a direction then a production ready PR
If we go ahead with this PR, we can keep the existing methods and mark deprecated , those methods will use the builder internally.
the benefits of this interface is that its fluent and achieves some code reuse.
Changes made
- I removed HttpApp from method args since its trivial for a user to wrap their HttpApp themselves and it really makes the underlying code more convoluted. We cannot run the conversion for them as we currently have a EffectCompat constraint on F while Client.fromHttpApp needs F[_]:Async. (@kubukoz says it doesnt really need it 🤷 ) .That said this does come with some …
=> Servicebuilder revised Feedback Requested

modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/bar/src/main/scala/Test.scala, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/bar/src/main/smithy/bar.smithy, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/build.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/foo/src/main/smithy/foo.smithy, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/project/build.properties, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/project/plugins.sbt, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-staged/test, modules/codegen/src/smithy4s/codegen/ModelLoader.scala
If users publish smithy4s generated code, we package the models in the artifacts for sharing with downstream projects. The problem has to do with Smithy4s not including its own models when loading upstream models, which do not necessarily depend on smithy4s-protocol.
This change adds the smithy4s-protocol model when loading upstream models, just in case.
Fixes https://github.com/disneystreaming/smithy4s/issues/420
=> Add smithy4s models to upstream model validation

build.sbt, modules/core/test/src-jvm/smithy4s/TimestampSpec.scala
I think this is the last module we can actually add Native support to - all the others have some JVM-only dependencies we won't be able to get rid of.
=> Decline: add native support

.github/workflows/ci.yml, modules/website/package.json, modules/website/yarn.lock
I can't explain why it does not work anymore. There are a bunch of open issues but I could not make sense of them.
I proceeded as follow:
* revert one dependabot commit
* `rm -rf .docusaurus node_modules/`
* run `yarn && yarn swizzle docusaurus-lunr-search SearchBar --danger --wrap && yarn build` (--wrap appears at some point)
* `yarn serve` (yarn start does not seem to work)
Closes #479
=> Pin docusaurus-lunr-search

modules/dynamic/src-jvm/DynamicSchemaIndexPlatform.scala
per https://github.com/awslabs/smithy/issues/1408 adding a Model Transformer sends the mixins to where they belong 
closes #453
=> added ModelTransformer to  flatten and merge all mixins in the model

modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/bar/src/main/scala/Test.scala, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/foo/src/main/smithy/foodir/foodir.smithy, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/test, modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala, modules/codegen/src/smithy4s/codegen/SmithyResources.scala, modules/mill-codegen-plugin/src/smithy4s/codegen/mill/Smithy4sModule.scala, modules/mill-codegen-plugin/test/resources/multi-module/bar/src/Test.scala, modules/mill-codegen-plugin/test/resources/multi-module/foo/smithy/foodir/foodir.smithy, modules/mill-codegen-plugin/test/src/smithy4s/codegen/mill/Smithy4sModuleSpec.scala
In 0.16.2, it seems like putting a Smithy file in a module breaks `smithy4sCodegen` of downstream modules. This will (hopefully) demonstrate that downstream modules fail to run codegen when such a situation arises.
The error is:
```
software.amazon.smithy.model.loader.ModelImportException: Unable to open Smithy model import URL: jar:file:/tmp/sbt_b32e5aac/foo/target/scala-2.13/foo_2.13-0.1.0-SNAPSHOT.jar!/META-INF/smithy/foodir
caused by
java.io.FileNotFoundException: JAR entry META-INF/smithy/foodir not found in /tmp/sbt_b32e5aac/foo/target/scala-2.13/foo_2.13-0.1.0-SNAPSHOT.jar
```
You can also reproduce this issue by trying to compile [this](https://github.com/kubukoz/demos/tree/smithy4s-subdir).
The generated manifest for this file structure:
```
smithy
- dir
| - coredir.smithy
``` …
=> Fix codegen resource outputs for Smithy files in subdirectories

modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/a.scala, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/bar/src/main/smithy/subdir/sub.smithy, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule/test, modules/codegen/src/smithy4s/codegen/SmithyResources.scala, modules/mill-codegen-plugin/test/resources/multi-module/bar/smithy/subdir/sub.smithy, modules/mill-codegen-plugin/test/src/smithy4s/codegen/mill/Smithy4sModuleSpec.scala
Closely related to #485, but can be resolved separately.
Might be worth a separate test to reduce the amount of moving parts in this one.
What happens here:
1. `bar` has a `.smithy` file in a subdirectory
2. `bar/smithy4sCodegen` runs
3. upstream changes (code changes or anything that forces `bar` to regenerate sources but apparently not things that directly impact `CodegenArgs`) happen
4. `bar/smithy4sCodegen` runs again: it fails because it's trying to overwrite files in `resources_managed` without removing them first
=> Remove stale generated resource directories

modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala
Service is now a class member in the ClientBuilder
This allows extending the ClientBuilder and utilizing the service in the extension methods
=> Adds Service as class member to Client builder 

modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/example-added.smithy, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/src/main/scala/Main.scala, modules/codegen-plugin/src/sbt-test/codegen-plugin/defaults/test, modules/codegen-plugin/src/smithy4s/codegen/JsonConverters.scala, modules/mill-codegen-plugin/test/src/smithy4s/codegen/mill/Smithy4sModuleSpec.scala
Fixes a regression from #485: in the sbt plugin, we now always pass just the path to the `smithy` directory (the default input directory for specs), and it turns out that the hashing implementation for directories doesn't look at the contents.
This PR ensures that we hash directories according to their contents (recursively), and adds some tests (for sbt/mill) to ensure we don't have bad cache hits and actually regenerate stuff when needed.
=> Codegen: Fix hashing for directories

modules/core/src/smithy4s/PolyFunction.scala, modules/core/src/smithy4s/capability/EncoderK.scala, modules/core/src/smithy4s/http/internals/ErrorCodeSchemaVisitor.scala, modules/core/src/smithy4s/schema/Alt.scala, modules/core/src/smithy4s/schema/Schema.scala, modules/core/test/src/smithy4s/PatternSpec.scala, modules/core/test/src/smithy4s/schema/HintsTransformationSpec.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sServerEndpoint.scala, modules/json/src/smithy4s/http/json/SchemaVisitorJCodec.scala
The transitive hints transformation was not accurately propagating hints wherever it needed. 
Additionally, this fixes the union Dispatcher construct, by caching on the labels as opposed to the instance, which aren't stable wrt hint transformation. 
This fixes the bug that makes https://github.com/disneystreaming/smithy4s/pull/521 red
=> Fix hint transformations and adds a test suite

modules/http4s/src/smithy4s/http4s/SimpleRestJsonBuilder.scala, modules/json/src/smithy4s/http/json/JsonCodecAPI.scala, modules/json/test/src/smithy4s/http/json/JsonCodecApiTests.scala
Previously, only top-level hints would be modified with the hint mask, so even if the mask was empty you could affect serialization with something like `@jsonName` or `@discriminated`.
This PR enables hint masks to work on all levels. This may possibly break existing behavior in users' code if they rely on the mask being applied only on the surface.
For such users, a workaround would be to use the `HintMask.allAllowed` mask in the codecs, but apply `.transformHintsLocally` with the old hint mask on the Schema directly.
=> Apply hint mask transitively in json codecs

modules/core/src/smithy4s/schema/CompilationCache.scala
When schema visitors are used as means to formulate typeclass instances, a global cache is used. It is risky to use non-thread-safe maps when that's the case. 
NB : I've not managed to trigger a bug, doesn't mean it wouldn't happen.
=> Use a concurrent map on JVM for the compilation cache

modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala, modules/http4s/test/src/smithy4s/http4s/ProtocolBuilderSpec.scala
Closes #501. The main issue would've been solved by #493, but even that PR doesn't address the eagerness problem of `as` - we shouldn't be building the whole router if it's not even going to be returned.
=> Build http4s routers lazily

modules/aws/src/smithy4s/aws/internals/AwsUnaryEndpoint.scala, modules/core/src/smithy4s/http/CodecAPI.scala, modules/core/src/smithy4s/http/Partial.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sClientEndpoint.scala, modules/http4s/src/smithy4s/http4s/internals/SmithyHttp4sServerEndpoint.scala, modules/json/test/src/smithy4s/http/json/JsonCodecApiTests.scala
Closes #594. Targetting main because this can be released in a patch release.
=> Catch PayloadErrors in complete decoding in CodecAPI

.github/workflows/ci.yml
For real this time. Follow-up to https://github.com/disneystreaming/smithy4s/pull/572.
We were still using setup-scala, which uses Jabba to get the JVM, and Jabba apparently doesn't know about Temurin at all.
Running this one manually here: https://github.com/disneystreaming/smithy4s/actions/runs/3439662770 (edit: gonna have to retry after the 0.16.8 publishing is done, because MiMa is failing)
=> Fix microsite, again

build.sbt, modules/codegen/src/smithy4s/codegen/IR.scala, modules/codegen/src/smithy4s/codegen/Renderer.scala, modules/codegen/src/smithy4s/codegen/SmithyToIR.scala, modules/codegen/src/smithy4s/codegen/ToLine.scala, modules/dynamic/src/smithy4s/dynamic/internals/DynamicModelCompiler.scala, modules/dynamic/test/src-jvm/smithy4s/dynamic/EnumSpec.scala, modules/example/src/smithy4s/example/DeprecatedService.scala, modules/example/src/smithy4s/example/DeprecatedString.scala, modules/example/src/smithy4s/example/DeprecatedStructure.scala, modules/example/src/smithy4s/example/DeprecatedUnion.scala, modules/example/src/smithy4s/example/EnumWithDeprecations.scala, modules/example/src/smithy4s/example/FaceCard.scala, modules/example/src/smithy4s/example/Launcher.scala, modules/example/src/smithy4s/example/Letters.scala, modules/example/src/smithy4s/example/LowHigh.scala, modules/example/src/smithy4s/example/Strings.scala, modules/example/src/smithy4s/example/SwitchState.scala, modules/example/src/smithy4s/example/package.scala, project/Smithy4sBuildPlugin.scala, sampleSpecs/deprecations.smithy
Made a separate commit for the actual implementation so that you can see how it affects the deprecated shapes:
[files in `modules/example` of this commit](https://github.com/disneystreaming/smithy4s/pull/599/commits/d5b5a818c078bfd29da959cc0772c130ccd55b84#diff-f6f31a8e21b138548e86cdaeadb003dd61d64575ca94b9a8ad5baa265f248556)
I think this doesn't have to go into 0.17 as it wouldn't make breaking changes.
Edit: about the above, I think this might be source breaking in a way (people might have fatal warnings on). Let's stick it into 0.17.
Solves the deprecation part of #256
=> Render deprecation hints

modules/compliance-tests/src-ce2/smithy4s/compliancetests/Compat.scala, modules/compliance-tests/src-ce3/smithy4s/compliancetests/Compat.scala, modules/compliance-tests/src/smithy4s/compliancetests/CompatUtils.scala, modules/compliance-tests/src/smithy4s/compliancetests/ComplianceTest.scala, modules/compliance-tests/src/smithy4s/compliancetests/HttpProtocolCompliance.scala, modules/compliance-tests/src/smithy4s/compliancetests/ReverseRouter.scala, modules/compliance-tests/src/smithy4s/compliancetests/Router.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ClientHttpComplianceTestCase.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ServerHttpComplianceTestCase.scala, modules/docs/markdown/03-protocols/05-compliance-tests.md, sampleSpecs/test.smithy
This branch targets `refine-compliance-tests-dx` and I assumed it was based on `series/0.17` so I merged that in. 
The only relevant commit in that PR is: https://github.com/disneystreaming/smithy4s/commit/ee22af5a51e1744a19a172f6e923b31a5f2173f9
=> Implement HttpProtocolCompliance w/o IO

modules/codegen-cli/src/smithy4s/codegen/cli/Main.scala, modules/codegen-cli/src/smithy4s/codegen/cli/Options.scala, modules/codegen-cli/test/src/smithy4s/codegen/cli/CommandParsingSpec.scala, modules/codegen-plugin/src/smithy4s/codegen/JsonConverters.scala, modules/codegen/src/smithy4s/codegen/Codegen.scala
References #571 
Also, took the initiative to rename `--localJars` to `--local-jars` so that all flags remain in the same style.
Looks like this:
```
./smithy4s-gen-test generate # built with `cs bootstrap`
Nothing was generated. Make sure your targetting Smithy files or folders that include Smithy definitions. Otherwise, you can also use --dependencies to pull external JARs or use --local-jars to use JARs located on your file system.
```
=> Add a message when no files are generated

modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala
Restores the previous default since `unmanagedSourceDirectories` is not what the average user would need and it causes some unexpected behavior depending on the build setup (as seen on some test projects).
=> smithy4sInputDirs more conservative default

modules/codegen/src/smithy4s/codegen/ModelLoader.scala
`Fetch()` uses the default cache, which is `FileCache().noCredentials`. I have no clue why that's the default, given `FileCache()` itself doesn't disable creds.
This enables the use of global credentials / environment variables / Java system properties.
Not easily testable without publishing something that requires credentials, so I'll trust in my manual testing.
=> Allow credentials in coursier Fetch in the model loader

modules/codegen-plugin/src/sbt-test/codegen-plugin/custom-settings/test, modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule-aws/test, modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala, modules/mill-codegen-plugin/src/smithy4s/codegen/mill/Smithy4sModule.scala
Unifies resolution (via the build tool's resolver) to ensure that there are no conflict resolved jars that are passed to the code-generator. This is done by gather all ModuleIDs before re-running the resolver, in order for it to perform the necessary eviction.
Thus, we only concatenate the jars that come from dependency resolution with the internal jars (which should hardly ever conflict).
Fixes https://github.com/disneystreaming/smithy4s/issues/644
=> Unifies resolution before codegen

modules/aws-http4s/src/smithy4s/aws/http4s/package.scala, modules/compliance-tests/src/smithy4s/compliancetests/HttpProtocolCompliance.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ClientHttpComplianceTestCase.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ServerHttpComplianceTestCase.scala, modules/core/src/smithy4s/Service.scala, modules/http4s/src/smithy4s/http4s/SimpleProtocolBuilder.scala, modules/test-utils/src/smithy4s/tests/JsonProtocolF.scala
I *think* the displacement of `Op` from parameter to member may have helped the tooling, and this is no longer needed
=> Remove the Service.Provider construct

build.sbt, modules/compliance-tests/src/smithy4s/compliancetests/internals/Assertions.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ClientHttpComplianceTestCase.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ServerHttpComplianceTestCase.scala, project/Dependencies.scala
adds dependency on circe for the Compliance tests module
detects when content type is json and the comparison is between 2 strings parse them first using a json parser to remove insignificant characters
=> Compliance tests jsonfix

build.sbt, modules/compliance-tests/src/smithy4s/compliancetests/internals/Assertions.scala, project/Dependencies.scala
If we are ok adding another library, Pprint is helpfult to present as clear evidence as possible of inequality between values when using the Compliance tests
=> add pprint library to compliance tests

modules/codegen-plugin/src/smithy4s/codegen/Smithy4sCodegenPlugin.scala
The absence of this information seems to trigger (hard to reproduce) edge-cases.
=> Pass scalaModuleInfo to dynamic resolution invocation

modules/compliance-tests/src/smithy4s/compliancetests/internals/ClientHttpComplianceTestCase.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/ServerHttpComplianceTestCase.scala, modules/compliance-tests/src/smithy4s/compliancetests/internals/package.scala
maps transitively the Hints on a schema and adds a Epoch timestamp format hint
=> fix for timestamp format issue for aws tests

modules/codegen/src/smithy4s/codegen/internals/SmithyToIR.scala, modules/core/test/src/smithy4s/ServiceWithResourcesSmokeSpec.scala, modules/core/test/src/smithy4s/TransformationSpec.scala, sampleSpecs/misc.smithy
When rendering a service, the resource operations are now gathered and added as if they were defined directly on a service.
=> Add resource operations to generated service
